name: scrapy
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - attrs=19.3.0=py_0
  - automat=20.2.0=py_0
  - backcall=0.1.0=py37_0
  - bcrypt=3.1.7
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_0
  - cffi=1.14.0
  - constantly=15.1.0=py_0
  - cryptography=2.8
  - cssselect=1.1.0=py_0
  - decorator=4.4.1=py_0
  - hyperlink=17.3.1=py_0
  - icu=64.2
  - idna=2.9=py_1
  - importlib_metadata=1.5.0=py37_0
  - incremental=17.5.0=py_0
  - ipython=7.12.0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.16.0=py37_0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libiconv=1.15
  - libstdcxx-ng=9.1.0
  - libxml2=2.9.10
  - libxslt=1.1.33
  - lxml=4.5.0
  - more-itertools=8.2.0=py_0
  - ncurses=6.2
  - openssl=1.1.1d
  - packaging=20.1=py_0
  - parsel=1.5.2=py37_0
  - parso=0.6.1=py_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=20.0.2=py37_1
  - pluggy=0.12.0=py_0
  - prompt_toolkit=3.0.3=py_0
  - protego=0.1.16=py_0
  - ptyprocess=0.6.0=py37_0
  - py=1.8.1=py_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_0
  - pydispatcher=2.0.5=py_1
  - pygments=2.5.2=py_0
  - pyhamcrest=2.0.2=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.6=py_0
  - pytest=5.3.5=py37_1
  - pytest-runner=5.2=py_0
  - python=3.7.6
  - queuelib=1.5.0=py37_0
  - readline=7.0
  - scrapy=2.0.0=py37_0
  - service_identity=18.1.0=py_0
  - setuptools=45.2.0=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1
  - tk=8.6.8
  - traitlets=4.3.3=py37_0
  - twisted=19.10.0
  - w3lib=1.20.0=py_0
  - wcwidth=0.1.8=py_0
  - wheel=0.34.2=py37_0
  - xz=5.2.4
  - zipp=3.1.0=py_0
  - zlib=1.2.11
  - zope.interface=4.7.1


